stages:
  - build

install-dependencies-job:
  stage: build
  script:
    - echo "Install npm dependencies"
    - sudo npm install

build-code-job:
  stage: build
  script:
    - echo "Run build"
    - sudo npm run build

copy-files-nginx-job:
  stage: build
  script:
    - echo "Remove old version and deploy"
    - sudo rm -R -i /var/www/html/*
    - sudo cp ./dist /var/www/html

restart-nginx-job:
  stage: build
  script:
    - echo "Restart nginx"
    - sudo systemctl reload nginx
